spring:
    datasource:
        url: ${ORDER_SPRING_DATASOURCE_URL}
        username: ${ORDER_SPRING_DATASOURCE_USERNAME}
        password: ${ORDER_SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: orderConfirmation:com.ovett.ecommerce.kafka.OrderConfirmation
server:
    port: ${ORDER_SERVICE_SERVER_PORT}
application:
    config:
        customer-url: ${CUSTOMER_SERVICE_URL}
        product-url: ${PRODUCT_SERVICE_URL}
        payment-url: ${PAYMENT_SERVICE_URL}