spring:
    datasource:
        url: ${ORDER_SPRING_DATASOURCE_URL}
        username: ${ORDER_SPRING_DATASOURCE_USERNAME}
        password: ${ORDER_SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: ${ORDER_SERVICE_SERVER_PORT}
application:
    config:
        customer-url: ${CUSTOMER_SERVICE_URL}
        product-url: ${PRODUCT_SERVICE_URL}
        payment-url: ${PAYMENT_SERVICE_URL}