spring:
    datasource:
        url: ${PAYMENT_SPRING_DATASOURCE_URL}
        username: ${PAYMENT_SPRING_DATASOURCE_USERNAME}
        password: ${PAYMENT_SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: paymentConfirmation:com.ovett.ecommerce.notification.PaymentNotificationRequest
server:
    port: ${PAYMENT_SERVICE_SERVER_PORT}
application:
    config:
        product-url: ${PRODUCT_SERVICE_URL}